apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-cluster
  namespace: rook
spec:
  dataDirHostPath: /var/lib/rook
  serviceAccount: rook-ceph-cluster
  network:
    hostNetwork: false
  dashboard:
    enabled: true
  # cluster level storage configuration and selection
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      metadataDevice:
    nodes:
      - name: "opti"
        devices: 
        - name: "sdb"
      - name: "congratulations"
        devices: 
        - name: "sdb"
