---
# Source: rook/templates/psp.yaml
# PSP for rook-operator

# Most of the teams follow the kubernetes docs and have these PSPs.
# * priviledged (for kube-system namespace)
# * restricted (for all logged in users)
#
# If we name it as `rook-operator`, it comes next to `restricted` PSP alphabetically,
# and applies `restricted` capabilities to `rook-system`. Thats reason this is named with `00-rook-operator`,
# so it stays somewhere close to top and `rook-system` gets the intended PSP.
#
# More info on PSP ordering : https://kubernetes.io/docs/concepts/policy/pod-security-policy/#policy-order

apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: 00-rook-operator
spec:
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - '*'
  hostPID: true
  hostIPC: true
  hostNetwork: true
---
# Source: rook/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    operator: rook
    chart: "rook-v0.7.0-136.gd13bc83"
  name: rook-operator
---
# Source: rook/templates/resources.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumeattachments.rook.io
spec:
  group: rook.io
  names:
    kind: VolumeAttachment
    listKind: VolumeAttachmentList
    plural: volumeattachments
    singular: volumeattachment
  scope: Namespaced
  version: v1alpha1
---
# Source: rook/templates/resources.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: filesystems.rook.io
spec:
  group: rook.io
  names:
    kind: Filesystem
    listKind: FilesystemList
    plural: filesystems
    singular: filesystem
  scope: Namespaced
  version: v1alpha1
---
# Source: rook/templates/resources.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: objectstores.rook.io
spec:
  group: rook.io
  names:
    kind: ObjectStore
    listKind: ObjectStoreList
    plural: objectstores
    singular: objectstore
  scope: Namespaced
  version: v1alpha1
---
# Source: rook/templates/resources.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pools.rook.io
spec:
  group: rook.io
  names:
    kind: Pool
    listKind: PoolList
    plural: pools
    singular: pool
  scope: Namespaced
  version: v1alpha1
---
# Source: rook/templates/resources.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.rook.io
spec:
  group: rook.io
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  version: v1alpha1
---
# Source: rook/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rook-operator
  labels:
    operator: rook
    chart: "rook-v0.7.0-136.gd13bc83"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-operator
  template:
    metadata:
      labels:
        app: rook-operator
        chart: "rook-v0.7.0-136.gd13bc83"
    spec:
      containers:
      - name: rook-operator
        image: "rook/rook:v0.7.0-136.gd13bc83"
        imagePullPolicy: IfNotPresent
        args:
          - operator
        env:
        - name: RBAC_ENABLED
          value: "false"
        - name: ROOK_LOG_LEVEL
          value: INFO
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROOK_MON_HEALTHCHECK_INTERVAL
          value: 45s
        - name: ROOK_MON_OUT_TIMEOUT
          value: 300s
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
