---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume
  labels:
    app: stress-test
spec:
  storageClassName: general
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100G
---
apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  namespace: rook-ceph
spec:
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: stress-test
    image: rook/ceph-toolbox:v0.8.1
    imagePullPolicy: IfNotPresent
    env:
      - name: ROOK_ADMIN_SECRET
        valueFrom:
          secretKeyRef:
            name: rook-ceph-mon
            key: admin-secret
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /dev
        name: dev
      - mountPath: /sys/bus
        name: sysbus
      - mountPath: /lib/modules
        name: libmodules
      - name: mon-endpoint-volume
        mountPath: /etc/rook
      - name: test-volume
        mountPath: /mnt
  hostNetwork: false
  volumes:
    - name: dev
      hostPath:
        path: /dev
    - name: sysbus
      hostPath:
        path: /sys/bus
    - name: libmodules
      hostPath:
        path: /lib/modules
    - name: test-volume
      persistentVolumeClaim:
         claimName: test-volume
    - name: mon-endpoint-volume
      configMap:
        name: rook-ceph-mon-endpoints
        items:
        - key: data
          path: mon-endpoints
