---
- hosts: all
  tasks:
  - systemd:
      name: firewalld
      enabled: yes
      state: started
    become: yes
  
- hosts: proxy
  roles:
    - proxy

- hosts: kube
  roles:
    - docker
    - kubernetes

- hosts: kube
  roles:
    - kubeadm-ha
