---
- hosts: all
  tasks:
  - systemd:
      name: firewalld
      enabled: no
      state: stopped
    become: yes

- hosts: all
  roles:
    - base

- hosts: proxy
  roles:
    - proxy

- hosts: storage
  roles:
    - storage

- hosts: kube
  roles:
    - docker
    - kubernetes

- hosts: kube-master
  roles:
    - kubeadm-ha
