---
- hosts: kube
  tasks:
  - systemd:
      name: firewalld
      enabled: no
      state: stopped
    become: yes
    when: ansible_distribution == 'Centos'

- hosts: kube
  roles:
    - base

- hosts: proxy
  roles:
    - proxy

- hosts: storage
  roles:
    - storage

- hosts: kube
  roles:
    - docker
    - kubernetes
