{
 "title": "ceph diagnosis",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Read Bytes - 1M Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "read bytes rate {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk Written Bytes - 1M Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "disk write rate {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Read Time Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total[1m])",
     "legendFormat": "read seconds rate {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "ODS Apply Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms", "legendFormat": "{{ceph_daemon}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_xfs_extent_allocation_extents_allocated_total"
    }
   ]
  }
 ]
}