{
 "title": "Couch",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(couchdb_httpd_database_reads[1m])",
     "legendFormat": "HTTP DB Reads"
    },
    {
     "expr": "rate(couchdb_httpd_database_writes[1m])",
     "legendFormat": "HTTP DB Writes"
    },
    {
     "expr": "rate(couchdb_httpd_requests[1m])",
     "legendFormat": "All HTTP Requests"
    }
   ]
  },
  {
   "title": "Couch Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{pod=~\"couch.*\", quantile=\"1\"}",
     "legendFormat": "Last GC Duration (seconds)"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{pod=~\"couch.*\"}",
     "legendFormat": "Heap Allocated"
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "couchdb_database_data_size", "legendFormat": "data size" },
    { "expr": "couchdb_database_disk_size", "legendFormat": "disk size" }
   ]
  }
 ]
}