{
 "title": "Econ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{pod=~\"econ.*\"}",
     "legendFormat": "heap used"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_max",
     "legendFormat": "heap max"
    }
   ]
  },
  {
   "title": "Send Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_producer_metrics_record_send_rate{pod=~\"econ.*\", client_id=~\"econ-streamer.*\"})",
     "legendFormat": "Stream Send Rate"
    },
    {
     "expr": "sum(kafka_producer_producer_metrics_record_send_rate{pod=~\"econ.*\", client_id=~\"producer.*\"})",
     "legendFormat": "Producer Send Rate"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"econ.*\"}[1m])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Receive Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{client_id=~\"econ-streamer.*\"})",
     "legendFormat": "Record Consume Rate - Streams"
    }
   ]
  }
 ]
}