{
 "title": "NodeZ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Load Averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "5 Min Load Avg - {{instance}}" }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"sd.\"}[1m])",
     "legendFormat": "Read {{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Network Rcv Bytes - 1 Min. Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"enp.*\"}[1m])",
     "legendFormat": "Receive - {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"sd.\"}[1m])",
     "legendFormat": "Write {{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Network Xmit Bytes - 1 Min. Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"enp.*\"}[1m])",
     "legendFormat": "Transmit - {{instance}} {{device}}"
    }
   ]
  }
 ]
}