{
 "title": "Node",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_memory_Active_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"} - (node_memory_MemFree_bytes{instance=\"$node\"} + node_memory_Buffers_bytes{instance=\"$node\"} + node_memory_Cached_bytes{instance=\"$node\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=\"$node\"}",
     "legendFormat": "5Min Load Avg"
    },
    {
     "expr": "node_load15{instance=\"$node\"}",
     "legendFormat": "15Min Load Avg"
    },
    {
     "expr": "node_procs_running{instance=\"$node\"}",
     "legendFormat": "Running Procs"
    },
    {
     "expr": "node_procs_blocked{instance=\"$node\"}",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_cpu_frequency_hertz{instance=\"$node\"}",
     "legendFormat": "CPU {{cpu}} Freq."
    },
    {
     "expr": "avg_over_time(node_cpu_frequency_hertz{instance=\"$node\"}[5m])",
     "legendFormat": "{{cpu}} 5 Min Avg"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\", device=~\"enp.*\"}[1m])",
     "legendFormat": "eth transmit"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\", device=~\"enp.*\"}[1m])",
     "legendFormat": "eth receive"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{instance=\"$node\", device=~\"enp.*\"}[1m])",
     "legendFormat": "transmit error rate"
    },
    {
     "expr": "rate(node_network_receive_errs_total{instance=\"$node\", device=~\"enp.*\"}[1m])",
     "legendFormat": "receive error rate"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\"}",
     "legendFormat": "CPU {{sensor}} Core Temp"
    },
    {
     "expr": "node_hwmon_power_watt{instance=\"$node\"}",
     "legendFormat": "{{sensor}} Power"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$node\", device=~\"sd.*\"}[1m])",
     "legendFormat": "{{device}} read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$node\", device=~\"sd.*\"}[1m])",
     "legendFormat": "{{device}} write bytes"
    }
   ]
  }
 ]
}