---
- name: ensure filesystems are prepared
  become: true
  filesystem:
    dev: "{{gluster_dev}}"
    fstype: "xfs"

- name: create mount points
  become: true
  file:
    path: /data/brick1
    state: directory

- name: mount brick
  become: true
  mount:
    path: /data/brick1
    fstype: xfs
    src: "{{gluster_dev}}"
    backup: yes
    state: mounted
    
- name: open gluster specific ports in the firewall
  become: true
  firewalld:
#    immediate: true
    permanent: true
    port: 111/tcp
    source: 192.168.1.0/24
    state: enabled
- firewalld:
#    immediate: true
    permanent: true
    port: 111/udp
    source: 192.168.1.0/24
    state: enabled
  become: true
- firewalld:
#    immediate: true
    permanent: true
    port: 24007/tcp
    source: 192.168.1.0/24
    state: enabled
  become: true
- firewalld:
#    immediate: true
    permanent: true
    port: 49152-50000/tcp
    source: 192.168.1.0/24
    state: enabled
  become: true

- name: Add gluster yum repository
  become: true
  yum:
    name: centos-release-gluster
    state: present

- name: Install gluster
  become: true
  yum:
    name: glusterfs,glusterfs-server
    state: present

- name: enable and start glusterd
  become: true
  systemd:
    name: glusterd
    state: started
    enabled: true
