
- name: install haproxy
  become: yes
  yum:
    name: haproxy-1.5.18
    state: present

- name: install keepalived
  become: yes
  yum:
    name: keepalived-1.3.5
    state: present

- name: keepalived config
  become: yes
  copy:
    src: files/keepalived-{{inventory_hostname}}.conf
    dest: /etc/keepalived/keepalived.conf
    mode: 0644

- name: keepalived daemon
  become: yes
  systemd:
    name: keepalived
    enabled: yes
    state: started

- name: haproxy config
  become: yes
  copy:
    src: files/haproxy-{{inventory_hostname}}.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: firewall rule for lb port
  become: yes
  firewalld:
    port: 6445/tcp
    permanent: true
    state: enabled

    #- name: firewall rule for keepalived
    #  become: yes
    #  command: "firewall-cmd --direct --permanent --add-rule ipv4 filter INPUT 0 --in-interface {{host_interface}} --destination 224.0.0.18 --protocol vrrp -j ACCEPT"

    #- become: yes
    #  command: "firewall-cmd --direct --permanent --add-rule ipv4 filter OUTPUT 0 --out-interface {{host_interface}} --destination 224.0.0.18 --protocol vrrp -j ACCEPT"

    #- name: reload firewall config
    #  become: yes
    #  systemd:
    #    name: firewalld
    #    state: restarted

- name: Ensure libsemanage-python installed
  become: yes
  yum:
    name: libsemanage-python-2.5
    state: present

    #- name: SELinux - allow haproxy to bind all
    #  become: yes
    #  seboolean:
    #    name: haproxy_connect_any
    #    state: yes
    #    persistent: yes

- name: haproxy daemon
  become: yes
  systemd:
    name: haproxy
    enabled: yes
    state: restarted

