apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-metric-collector
  namespace: monitoring
  labels:
    team: rook
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-state-metrics
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
