
- name: add the kubernetes yum repo
  become: true
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  when: ansible_distribution == 'Centos'

- name: add kubernetes key to apt-keys
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: add the kubernetes apt repo
  become: true
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: disable selinux for next boot
  become: true
  selinux:
    state: disabled
  when: ansible_distribution == 'Centos'

- name: disable swap
  become: true
  command: swapoff -a
- mount:
    name: swap
    fstype: swap
    state: absent
  become: true

- name: ensure bridge-nf-call is enabled
  become: true
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    reload: yes
- sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present
    reload: yes
  become: true

- name: open kube ports in firewall
  become: true
  firewalld:
#    immediate: true
    permanent: true
    port: 6443/tcp
    source: 192.168.1.0/24
    state: enabled
  when: ansible_distribution == 'Centos'
- firewalld:
#    immediate: true
    permanent: true
    port: 2379-2380/tcp
    source: 192.168.1.0/24
    state: enabled
  become: true
  when: ansible_distribution == 'Centos'
- firewalld:
##    immediate: true
    permanent: true
    port: 10250/tcp
    source: 192.168.1.0/24
    state: enabled
  become: true
  when: ansible_distribution == 'Centos'
- firewalld:
#    immediate: true
    permanent: true
    port: 10251/tcp
    source: 192.168.1.0/24
    state: enabled
  become: true
  when: ansible_distribution == 'Centos'
- firewalld:
#    immediate: true
    permanent: true
    port: 10252/tcp
    source: 192.168.1.0/24
    state: enabled
  become: true
  when: ansible_distribution == 'Centos'
- firewalld:
#    immediate: true
    permanent: true
    port: 10255/tcp
    source: 192.168.1.0/24
    state: enabled
  become: true
  when: ansible_distribution == 'Centos'
- firewalld:
#    immediate: true
    permanent: true
    port: 10256/tcp
    source: 192.168.1.0/24
    state: enabled
  become: true
  when: ansible_distribution == 'Centos'
- firewalld:
#    immediate: true
    permanent: true
    port: 8285/udp
    source: 192.168.1.0/24
    state: enabled
  become: true
  when: ansible_distribution == 'Centos'
- firewalld:
#    immediate: true
    permanent: true
    port: 8472/udp
    source: 192.168.1.0/24
    state: enabled
  become: true
  when: ansible_distribution == 'Centos'
#- name: allow docker0 interface
#  firewalld:
#    immediate: true
#  permanent: true
#    interface: docker0
#    zone: trusted
#    state: enabled
#  become: true

- name: install kubelet
  become: true
  package:
    name: kubelet
    state: present

- name: install kubeadm
  become: true
  package:
    name: kubeadm
    state: present

- name: install kubectl
  become: true
  package:
    name: kubectl
    state: present

- name: enable kube services
  become: true
  systemd:
    name: kubelet
    state: started
    enabled: true 
