apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
apiServer:
  CertSANs:
  - "kube-cluster"
controlPlaneEndpoint: "kube-cluster:6445"
networking:
  podSubnet: 10.244.0.0/16
