- name: Add docker yum repository
  become: yes
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_distribution == 'Centos'

- name: add docker key to apt-keys
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

# TODO: make release ('cosmic') a variable
- name: add docker apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu cosmic stable"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: update apt cache
  become: yes
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install docker
  become: yes
  package:
    name: docker-ce
    state: present

    #- name: install docker-compose
    #  become: yes
    #  shell: curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

    #- name: set docker-compose executable
    #  become: yes
    #  file: dest=/usr/local/bin/docker-compose mode=a+x

- name: ensure etc/docker exists
  become: yes
  file:
    path: /etc/docker
    state: directory
    mode: 0700

- name: install daemon.json file
  become: yes
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    backup: yes

- name: enable and run dockerd
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes
